config/routes.rb
Rails.application.routes.draw do

  get 'messages/new'

  get 'sessions/new'

  get 'auth/:provider/callback' => 'sessions#callback' , as: :auth_callback

  root 'home#index'
  get 'login' => 'sessions#new'
  post 'new_session' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'sent_messages' => 'home#sent_messages'
  get 'friends' => 'home#friends'
  get 'user_list' => 'home#user_list'

  resources :users
  resources :messages, only: [:new, :show,:index, :create, :destroy]

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if logged_in?
      @messages = current_user.messages_received
    end
  end

  def sent_messages
    @messages = current_user.messages
  end

  def friends
    @friends = []
    unless friend_list.blank?
      friend_list.each do |f|
        @friends << User.find_by_id(f)
      end
    end 
  end

  def user_list
    @users = User.all
    @friend_list = friend_list
    @block_list = block_list
    unless params[:add_friend].blank?
      @friend_list << params[:add_friend]
      current_user.update(friend_list: @friend_list.join(" "))
      flash[:success] = "Add friend successful"
      redirect_to friends_path
    end
    unless params[:remove_friend].blank?
      @friend_list.delete(params[:remove_friend])
      current_user.update(friend_list: @friend_list.join(" "))
      flash[:success] = "Remove friend successful"
      redirect_to friends_path
    end
    unless params[:block].blank?
      @block_list << params[:block]
      current_user.update(block_list: @block_list.join(" "))
      flash[:success] = "Block successful"
      redirect_to user_list_path
    end
    unless params[:unblock].blank?
      @block_list.delete(params[:unblock])
      current_user.update(block_list: @block_list.join(" "))
      flash[:success] = "Unblock successful"
      redirect_to user_list_path
    end
  end

  private
    def friend_list
      friend_list = []
      list ||= current_user.friend_list.split(" ")
      list.each do |l|
        friend_list << l
      end
      friend_list
    end

    def block_list
      block_list = []
      list ||= current_user.block_list.split(" ")
      list.each do |l|
        block_list << l
      end
      block_list
    end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/friends.html.erb
<div class="jumbotron jumbotron-fluid" style= "background-color: #563d7c; color: #fff">
  <h1 class="display-3 text-xs-center">Friend List</h1>
</div>
<% if @friend.blank? %>
<div class="list-group clearfix" style="line-height:30px">
  <% @friends.each do |f| %>
    <div class="list-group-item">
      <div class="pull-xs-right">
        <%= link_to "Send Message", new_message_path(recipient_email: f.email),
          class:"btn btn-secondary-outline btn-sm" %>
        <%= link_to "Remove", user_list_path(remove_friend: f.id), 
          class:"btn btn-secondary-outline btn-sm" %>
      </div>
     <%= f.name %>: <%= f.email %>
    </div>
  <% end %>
</div>
<% else %>
  <h2>Your friend list is empty </h2>
<% end %>
  <hr>
  <div class="col-xs-12">
    <%= link_to "Add new friend", user_list_path, class: "btn btn-secondary" %>
    <%= link_to "Block User", '#', class: "btn btn-secondary pull-xs-right" %>
  </div>

app/views/home/index.html.erb
<% if logged_in? %>
  <div class="jumbotron jumbotron-fluid" style="background-color: #563d7c">
    <h1 class="display-4 text-xs-center" style="color: #fff" >
      Wellcome 
    </h1>
    <div class="lead text-xs-center" style="color:#cdbfe3">
      <strong><%= current_user.name  %></strong>,
      you have <%= pluralize(unread_message(current_user.notifications),"unread message") %> <br>
      <br>
    </div>
        <div class="text-xs-center">
          <div class="btn-group">
            <%= link_to "New Message", new_message_path, class:"btn btn-secondary btn-lg" %> 
            <%= link_to "Inbox", messages_path, class:"btn btn-secondary btn-lg"%> 
            <%= link_to "Outbox", sent_messages_path, class:"btn btn-secondary btn-lg"%> 
          </div>
        </div>
  </div>
<% else %>
  <div class="jumbotron jumbotron-fluid" style="background-color: #563d7c">
    <h1 class="display-4 text-xs-center" style="color: #fff" >
      Wellcome 
    </h1>
      <div class="lead text-xs-center" style="color:#cdbfe3">
        You need register or sign in before start using Coder Chat app
        <br>
        <br>
    </div>
        <div class="text-xs-center">
          <div class="btn-group">
            <%= link_to "Register", new_user_path, class:"btn btn-secondary btn-lg" %> 
            <%= link_to "Sign In", login_path, class:"btn btn-secondary btn-lg"%> 
            <%= link_to "Sign In with Facebook", "/auth/facebook", class:"btn btn-secondary btn-lg"%> 
          </div>
        </div>
  </div>
<% end %>

app/views/home/sent_messages.html.erb
<div class="jumbotron jumbotron-fluid" style= "background-color: #563d7c; color: #fff">
  <h1 class="display-3 text-xs-center">Outbox</h1>
</div>
<% if !@messages.blank? %>
  <ul class="list-group">
    <% @messages.each do |m| %>
      <% unless has_read? m %>
        <li class="list-group-item"> 
          <strong>
            Message has been sent to <%= recipient_of_message(m).email %> at: 
            <%= format_time(m.created_at) %>
            <div class="pull-xs-right">
              Unread
            </div>
          </strong>
      </li>
      <% else %>
        <li class="list-group-item disabled"> Message to <%= recipient_of_message(m).email %> has been read at: 
                            <%= format_time(m.notification.updated_at) %>
        <div class="pull-xs-right">
          Has read
        </div>
        </li>
      <% end %>
    <% end %>
  </ul>
<% else %>
  <h2 class="text-xs-center"> Your outbox is empty</h2>
<% end %>
<hr>
<div class="text-xs-center">
  <%= link_to "Send Message", new_message_path, class:"btn btn-secondary btn-lg" %>
</div>

app/views/home/user_list.html.erb
<div class="jumbotron jumbotron-fluid" style= "background-color: #563d7c; color: #fff">
  <h1 class="display-3 text-xs-center">User list</h1>
</div>
<div class="list-group">
  <% @users.each do |user| %>
    <div class="list-group-item">
    <div class="pull-xs-right">
	    <%= link_to "Send Message", new_message_path(recipient_email: user.email), class:"btn btn-secondary-outline btn-sm" %>
      <%unless @friend_list.include? user.id.to_s  %>
        <%= link_to "Add friend", user_list_path(add_friend: user.id), 
          class:"btn btn-secondary-outline btn-sm" %>
      <% else %>
        <%= link_to "Remove friend",user_list_path(remove_friend: user.id) , 
          class:"btn btn-secondary-outline btn-sm" %>
      <% end %>
      <%unless @block_list.include? user.id.to_s  %>
        <%= link_to "Block", user_list_path(block: user.id), 
          class:"btn btn-secondary-outline btn-sm" %>
      <% else %>
        <%= link_to "Unblock",user_list_path(unblock: user.id) , 
          class:"btn btn-secondary-outline btn-sm" %>
      <% end %>
	  </div>
      <%= user.name %> <div class="text-muted"><%= user.email %></div>
    </div>
    
  <% end %>