config/routes.rb
Rails.application.routes.draw do

  get 'messages/new'

  get 'sessions/new'

  get 'auth/:provider/callback' => 'sessions#callback' , as: :auth_callback

  root 'home#index'
  get 'login' => 'sessions#new'
  post 'new_session' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'sent_messages' => 'home#sent_messages'
  get 'friends' => 'home#friends'
  get 'user_list' => 'home#user_list'

  resources :users
  resources :messages, only: [:new, :show,:index, :create, :destroy]

end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-light bg-faded">
  <%= link_to "Coder Chat", root_path, class: "navbar-brand" %>
  <ul class="nav navbar-nav">
  <% unless logged_in? %>  
    <li class="nav-item active">
      <%= link_to "Sign In", login_path, class:"nav-link" %>
    </li>
    <li class="nav-item active">
      <%= link_to "Sign Up", new_user_path, class:"nav-link" %>
    </li>
  <% else %>
    <div class="pull-xs-right">
    <li class="nav-item">
      <%= link_to "#{pluralize(unread_message(current_user.notifications),"unread message")}", 
        messages_path, class:"nav-link"%>  
    </li>
    <li class="nav-item dropdown">
         <%= link_to "#{current_user.name}", root_path, role:"button", 
           data: {toggle: "dropdown"}, aria: {haspopup: "true", expaded: "false"}, 
           class: "nav-link dropdown-toggle", id: "Preview" %>
         <div class="dropdown-menu" aria-labelledby="dropdownMenu1">
           <%= link_to "New Message", new_message_path, class: "dropdown-item" %>
           <%= link_to "User list", user_list_path, class: "dropdown-item" %>
           <%= link_to "Friend list", friends_path, class: "dropdown-item" %>
           <%= link_to "Inbox", messages_path, class: "dropdown-item" %>
           <%= link_to "Outbox", sent_messages_path, class: "dropdown-item" %>
           <div class="dropdown-divider"></div>
           <%= link_to "Logout", logout_path, method: :delete, class:"dropdown-item" %>
         </div>
    </li>
    </div>
  <% end %>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Coder Chat</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">
    <%= render 'layouts/navbar' %>
    <br>
    <%= flash_messages %>
    <%= yield %>
  </div>

</body>
</html>